FROM node:14-alpine AS builder
WORKDIR /app
COPY package.json .
RUN yarn
COPY . .
RUN yarn build

FROM node:14-apline
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/dist ./dist
CMD yarn start:prod